language: rust
cache: cargo
rust:
  - stable

before_cache:
  - chmod -R a+r $HOME/.cargo

env:
- RUST_TEST_THREADS=1

before_script:
- export PATH="$HOME/.cargo/bin:$PATH"
- rustup component add rustfmt
- rustup component add clippy

script:
  - cargo fmt --all -- --check `find src -iname "*.rs"`
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo clippy --verbose --release -- -D clippy::all
